User-agent: *
Allow: *
Disallow: /admin/
Disallow: /files/
Disallow: /Products*
Disallow: /products*
Allow: /zapchasti*
Sitemap: https://<?=Configure::read('domain.url')?>/sitemap.xml
Host: <?=Configure::read('domain.url')?>