User-agent: *
Disallow: /admin/
Disallow: /js/
Disallow: /files/
Disallow: /products/
Disallow: /zapchasti$
Disallow: /autozapchasti
Sitemap: http://<?=Configure::read('domain.url')?>/sitemap.xml
Host: <?=Configure::read('domain.url')?>